# Generated by Django 4.2.1 on 2023-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='nada', max_length=300, verbose_name='Descripcion'),
        ),
    ]
